### PR TITLE
Key and Door/Collectible Demo

### PR DESCRIPTION
**Pull request by apl14**
I  made a simple “key and door” game which has 5 collectibles, one of
which is blocked off by a door. In order to win, the player must
collect all 5 collectibles. Once the player has done so, a message will
appear saying the player has won the game.

### CODE REVIEW

**Comment by mjl71** [comment]
Is this request no longer needed?

**Comment by apl14** [comment]
I'm not sure yet I need to double check with Dillon after class today.
_______________________________________

**Comment by mjl71** [comment]
Merge completed manually.

**Comment by DustyGreen64** [comment]
frick u

**Pull request closed without merging**
